name: Backend Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '18'

    - name: Build with Gradle and test
      run: chmod +x gradlew && ./gradlew wrapper --gradle-version 8.0 --distribution-type bin && ./gradlew wrapper && ./gradlew build && ./gradlew test

    - name: run the run.sh file
      run: bash ./run.sh
      
    - name: SonarQube analysis
      run: ./gradlew sonarqube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Execute remote SSH commands
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          echo "Hello World"

    - name: Copy script to remote server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        source: "run.sh"  # Update with your script name
        target: "./" 
